#!/bin/bash

set -eu
. /opt/crab/crab_utils/bin/::carbon.sys

[ "${1:-}" = "--help" ] && sys::usage "$@"
### --help Info: тестирование crab_syntax через
### --help /opt/crab/crab_utils/test/test-crab_syntax.white
### --help и /opt/crab/crab_utils/test/test-crab_syntax.black
### --help Usage:
### --help Example: test-crab_syntax


failed=FALSE

if ! /opt/crab/crab_utils/bin/crab_syntax \
	/opt/crab/crab_utils/test/test-crab_syntax.white; then
	failed=TRUE
fi

/opt/crab/crab_utils/bin/crab_syntax \
	/opt/crab/crab_utils/test/test-crab_syntax.black &>/tmp/test-crab_syntax.$$ || true

check_funcs=$( cat /opt/crab/crab_utils/bin/crab_syntax \
	| grep 'strongbash[0-9][0-9][0-9][_]*[0-9]*()' \
	| sed -n  's/^\(strongbash[0-9_]\{3,5\}\).*/\1/p' ) # '
for func in $check_funcs; do
	if ! grep -qwm1 "$func" /tmp/test-crab_syntax.$$; then
		echo "TEST $0 $func not found in "\
			"/opt/crab/crab_utils/test/test-crab_syntax.black [ FAILED ]"
		failed=TRUE
	fi
done

for func in $check_funcs; do
	if ! grep -qwm1 "$func" /opt/crab/crab_utils/test/test-crab_syntax.white; then
		echo "TEST $0 $func not found in "\
			"/opt/crab/crab_utils/test/test-crab_syntax.white [ FAILED ]"
		failed=TRUE
	fi
done

rm -f /tmp/test-crab_syntax.$$

if [ $failed = TRUE ]; then
	exit 1
fi

exit 0
