#!/bin/bash

set -eu
. /opt/crab/crab_utils/bin/::carbon.sys

[ "${1:-}" = "--help" ] && sys::usage "$@"
### --help Info: тестирование test-crab_indent через
### --help /opt/crab/crab_utils/test/test-crab_indent.white
### --help Usage:
### --help Example: test-crab_indent


cp -a /opt/crab/crab_utils/test/test-crab_indent.white /tmp/test-crab_indent.white.$$

failed=FALSE
/opt/crab/crab_utils/bin/crab_indent /tmp/test-crab_indent.white.$$
diff -U 10 /opt/crab/crab_utils/test/test-crab_indent.white \
	/tmp/test-crab_indent.white.$$ || failed=TRUE
rm -f /tmp/test-crab_indent.white.$$

if [ $failed = TRUE ]; then
	echo "TEST $0 /opt/crab/crab_utils/test/test-crab_indent.white [ FAILED ]"
	exit 1
fi

exit 0
