#!/bin/bash

set -eu
{
	failed=FALSE
	{
		if ! /opt/crab/crab_syntax /opt/crab/test/test-crab_syntax.white; then
			echo TEST $0 /opt/crab/test/test-crab_syntax.white [ FAILED ]
			failed=TRUE
		fi
	}

	/opt/crab/crab_syntax /opt/crab/test/test-crab_syntax.black &>/tmp/test-crab_syntax.$$ || true

	check_funcs=$( cat /opt/crab/crab_syntax | grep 'bash[0-9][0-9][0-9]()' | sed -n  's/^\(bash[0-9]\{3\}\).*/\1/p' ) # '

	for func in $check_funcs; do
		if ! grep -qm1 "$func" /tmp/test-crab_syntax.$$; then
			echo TEST $0 $func not found in /opt/crab/test/test-crab_syntax.black [ FAILED ]
			failed=TRUE
		fi
	done

	rm -f /tmp/test-crab_syntax.$$
} &>/tmp/test-crab_syntax_out.$$

if [ $failed = TRUE ]; then
	cat /tmp/test-crab_syntax_out.$$
	rm -f /tmp/test-crab_syntax_out.$$
	exit 1
fi

rm -f /tmp/test-crab_syntax_out.$$
echo SUCCESS
exit 0
