os: linux
  
install: ls -la && git clone https://github.com/strizhechenko/crab_utils /opt/crab_utils/ && /opt/crab/utils/crab_update

script:
  - crab_indent --help
  - crab_syntax --help
  - crab_example --help
