language: python

os: linux

python:
  - "3.6"

install: mkdir -p /opt/crab && cp -a . /opt/crab/crab_utils && sudo /opt/crab/crab_utils/bin/crab_update

script:
  - crab_indent --help
  - crab_syntax --help
  - crab_example --help
  - /opt/crab/crab_utils/autotest
