#!/bin/bash
##

set -eu
. /opt/crab/crab_utils/bin/crab_sys.sh

[ "${1:-}" = "--help" ] && sys::usage "$@"
### --help Info: запуск тестов foreach /opt/crab/crab_utils/test/test-*
### --help Usage:
### --help Example: autotest

err=0

if ! /opt/crab/crab_utils/bin/crab_syntax /opt/crab/crab_utils; then
	err=$((err+1))
fi
for test in /opt/crab/crab_utils/test/test-*; do
	[ ! -x $test ] && continue
	echo
	if ! $test; then
		err=$((err+1))
	fi
done


[ $err != 0 ] && exit 1

exit 0
