#!/usr/bin/env python
""" TODO: опишите, что это за скрипт """

import argparse


def parse_args():
    """ Разбор аргументов"""
    parser = argparse.ArgumentParser()
    parser.description = "Опишите, что делает утилита"
    parser.add_argument('-o', '--option', default=1, type=int, help='Описание опции')
    parser.add_argument('--flag', action='store_true', default=True, help="Описание флага.")
    parser.add_argument('--no-flag', action='store_false', default=False, dest="flag",
                        help="Описание флага.")
    return parser.parse_args()


def func1(args):
    print(args)


def main():
    args = parse_args()
    func1(args)


if __name__ == '__main__':
    main()
