#!/usr/bin/env python3
""" TODO: опишите, что это за скрипт """
# coding: utf-8

import argparse
import logging


def parse_args():
    """ Разбор аргументов"""
    parser = argparse.ArgumentParser()
    parser.description = "Опишите, что делает утилита"
    parser.add_argument('-o', '--option', default=1, type=int, help='Описание опции')
    parser.add_argument('--debug', action='store_true', default=False, help="Включить отладочное логирование.")
    parser.add_argument('--silent', action='store_true', default=False, help="Оставить только warning/error логи.")
    return parser.parse_args()


def func1(args):
    print(args)


def main():
    args = parse_args()
    logging.basicConfig(level=(logging.DEBUG if args.debug else logging.WARNING if args.silent else logging.INFO),
                        format="[%(filename)s:%(lineno)s - %(funcName)20s() ] %(message)s")
    func1(args)


if __name__ == '__main__':
    main()
